<table>
    <thead>
    <tr>
        <th></th>
        <th></th>
        <th>On ART</th>
        <th colspan="3">Defaulted</th>
        <th>Stopped</th>
        <th>Died</th>
        <th>Transferred Out</th>
        <th>Total</th>
    </tr>
    <tr>
        <th></th>
        <th></th>
        <th>(TX_CURR)</th>
        <th>1 Month</th>
        <th>2 Months</th>
        <th>3+ Months</th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <th>TOTAL</th>
        <th></th>
        <th>{{$data['txCurrent']['total']}}</th>
        <th>{{$data['defaulted1Month']['total']}}</th>
        <th>{{$data['defaulted2Months']['total']}}</th>
        <th>{{$data['defaulted3MonthsPlus']['total']}}</th>
        <th>{{$data['stopped']['total']}}</th>
        <th>{{$data['died']['total']}}</th>
        <th>{{$data['transferredOut']['total']}}</th>
        <th>{{$data['everRegistared']['total']}}</th>
    </tr>
    <tr>
        <th>Adults</th>
        <th></th>
        <th>{{$data['txCurrent']['adults']['count']}}</th>
        <th>{{$data['defaulted1Month']['adults']['count']}}</th>
        <th>{{$data['defaulted2Months']['adults']['count']}}</th>
        <th>{{$data['defaulted3MonthsPlus']['adults']['count']}}</th>
        <th>{{$data['stopped']['adults']['count']}}</th>
        <th>{{$data['died']['adults']['count']}}</th>
        <th>{{$data['transferredOut']['adults']['count']}}</th>
        <th>{{$data['everRegistared']['adults']['count']}}</th>
    </tr>
    <tr>
        <th>Males</th>
        <th></th>
        <th>{{$data['txCurrent']['adults']['males']['count']}}</th>
        <th>{{$data['defaulted1Month']['adults']['males']['count']}}</th>
        <th>{{$data['defaulted2Months']['adults']['males']['count']}}</th>
        <th>{{$data['defaulted3MonthsPlus']['adults']['males']['count']}}</th>
        <th>{{$data['stopped']['adults']['males']['count']}}</th>
        <th>{{$data['died']['adults']['males']['count']}}</th>
        <th>{{$data['transferredOut']['adults']['males']['count']}}</th>
        <th>{{$data['everRegistared']['adults']['males']['count']}}</th>
    </tr>
    <tr>
        <th></th>
        <th>15-19</th>
        <th>{{$data['txCurrent']['adults']['males']['disaggregatedByAge']['15-19']}}</th>
        <th>{{$data['defaulted1Month']['adults']['males']['disaggregatedByAge']['15-19']}}</th>
        <th>{{$data['defaulted2Months']['adults']['males']['disaggregatedByAge']['15-19']}}</th>
        <th>{{$data['defaulted3MonthsPlus']['adults']['males']['disaggregatedByAge']['15-19']}}</th>
        <th>{{$data['stopped']['adults']['males']['disaggregatedByAge']['15-19']}}</th>
        <th>{{$data['died']['adults']['males']['disaggregatedByAge']['15-19']}}</th>
        <th>{{$data['transferredOut']['adults']['males']['disaggregatedByAge']['15-19']}}</th>
        <th>{{$data['everRegistared']['adults']['males']['disaggregatedByAge']['15-19']}}</th>
    </tr>
    <tr>
        <th></th>
        <th>20-24</th>
        <th>{{$data['txCurrent']['adults']['males']['disaggregatedByAge']['20-24']}}</th>
        <th>{{$data['defaulted1Month']['adults']['males']['disaggregatedByAge']['20-24']}}</th>
        <th>{{$data['defaulted2Months']['adults']['males']['disaggregatedByAge']['20-24']}}</th>
        <th>{{$data['defaulted3MonthsPlus']['adults']['males']['disaggregatedByAge']['20-24']}}</th>
        <th>{{$data['stopped']['adults']['males']['disaggregatedByAge']['20-24']}}</th>
        <th>{{$data['died']['adults']['males']['disaggregatedByAge']['20-24']}}</th>
        <th>{{$data['transferredOut']['adults']['males']['disaggregatedByAge']['20-24']}}</th>
        <th>{{$data['everRegistared']['adults']['males']['disaggregatedByAge']['20-24']}}</th>
    </tr>
    <tr>
        <th></th>
        <th>25-29</th>
        <th>{{$data['txCurrent']['adults']['males']['disaggregatedByAge']['25-29']}}</th>
        <th>{{$data['defaulted1Month']['adults']['males']['disaggregatedByAge']['25-29']}}</th>
        <th>{{$data['defaulted2Months']['adults']['males']['disaggregatedByAge']['25-29']}}</th>
        <th>{{$data['defaulted3MonthsPlus']['adults']['males']['disaggregatedByAge']['25-29']}}</th>
        <th>{{$data['stopped']['adults']['males']['disaggregatedByAge']['25-29']}}</th>
        <th>{{$data['died']['adults']['males']['disaggregatedByAge']['25-29']}}</th>
        <th>{{$data['transferredOut']['adults']['males']['disaggregatedByAge']['25-29']}}</th>
        <th>{{$data['everRegistared']['adults']['males']['disaggregatedByAge']['25-29']}}</th>
    </tr>

    <tr>
        <th></th>
        <th>30-34</th>
        <th>{{$data['txCurrent']['adults']['males']['disaggregatedByAge']['30-34']}}</th>
        <th>{{$data['defaulted1Month']['adults']['males']['disaggregatedByAge']['30-34']}}</th>
        <th>{{$data['defaulted2Months']['adults']['males']['disaggregatedByAge']['30-34']}}</th>
        <th>{{$data['defaulted3MonthsPlus']['adults']['males']['disaggregatedByAge']['30-34']}}</th>
        <th>{{$data['stopped']['adults']['males']['disaggregatedByAge']['30-34']}}</th>
        <th>{{$data['died']['adults']['males']['disaggregatedByAge']['30-34']}}</th>
        <th>{{$data['transferredOut']['adults']['males']['disaggregatedByAge']['30-34']}}</th>
        <th>{{$data['everRegistared']['adults']['males']['disaggregatedByAge']['30-34']}}</th>
    </tr>

    <tr>
        <th></th>
        <th>35-39</th>
        <th>{{$data['txCurrent']['adults']['males']['disaggregatedByAge']['35-39']}}</th>
        <th>{{$data['defaulted1Month']['adults']['males']['disaggregatedByAge']['35-39']}}</th>
        <th>{{$data['defaulted2Months']['adults']['males']['disaggregatedByAge']['35-39']}}</th>
        <th>{{$data['defaulted3MonthsPlus']['adults']['males']['disaggregatedByAge']['35-39']}}</th>
        <th>{{$data['stopped']['adults']['males']['disaggregatedByAge']['35-39']}}</th>
        <th>{{$data['died']['adults']['males']['disaggregatedByAge']['35-39']}}</th>
        <th>{{$data['transferredOut']['adults']['males']['disaggregatedByAge']['35-39']}}</th>
        <th>{{$data['everRegistared']['adults']['males']['disaggregatedByAge']['35-39']}}</th>
    </tr>

    <tr>
        <th></th>
        <th>40-44</th>
        <th>{{$data['txCurrent']['adults']['males']['disaggregatedByAge']['40-44']}}</th>
        <th>{{$data['defaulted1Month']['adults']['males']['disaggregatedByAge']['40-44']}}</th>
        <th>{{$data['defaulted2Months']['adults']['males']['disaggregatedByAge']['40-44']}}</th>
        <th>{{$data['defaulted3MonthsPlus']['adults']['males']['disaggregatedByAge']['40-44']}}</th>
        <th>{{$data['stopped']['adults']['males']['disaggregatedByAge']['40-44']}}</th>
        <th>{{$data['died']['adults']['males']['disaggregatedByAge']['40-44']}}</th>
        <th>{{$data['transferredOut']['adults']['males']['disaggregatedByAge']['40-44']}}</th>
        <th>{{$data['everRegistared']['adults']['males']['disaggregatedByAge']['40-44']}}</th>
    </tr>

    <tr>
        <th></th>
        <th>45-49</th>
        <th>{{$data['txCurrent']['adults']['males']['disaggregatedByAge']['45-49']}}</th>
        <th>{{$data['defaulted1Month']['adults']['males']['disaggregatedByAge']['45-49']}}</th>
        <th>{{$data['defaulted2Months']['adults']['males']['disaggregatedByAge']['45-49']}}</th>
        <th>{{$data['defaulted3MonthsPlus']['adults']['males']['disaggregatedByAge']['45-49']}}</th>
        <th>{{$data['stopped']['adults']['males']['disaggregatedByAge']['45-49']}}</th>
        <th>{{$data['died']['adults']['males']['disaggregatedByAge']['45-49']}}</th>
        <th>{{$data['transferredOut']['adults']['males']['disaggregatedByAge']['45-49']}}</th>
        <th>{{$data['everRegistared']['adults']['males']['disaggregatedByAge']['45-49']}}</th>
    </tr>
    <tr>
        <th></th>
        <th>50+</th>
        <th>{{$data['txCurrent']['adults']['males']['disaggregatedByAge']['50+']}}</th>
        <th>{{$data['defaulted1Month']['adults']['males']['disaggregatedByAge']['50+']}}</th>
        <th>{{$data['defaulted2Months']['adults']['males']['disaggregatedByAge']['50+']}}</th>
        <th>{{$data['defaulted3MonthsPlus']['adults']['males']['disaggregatedByAge']['50+']}}</th>
        <th>{{$data['stopped']['adults']['males']['disaggregatedByAge']['50+']}}</th>
        <th>{{$data['died']['adults']['males']['disaggregatedByAge']['50+']}}</th>
        <th>{{$data['transferredOut']['adults']['males']['disaggregatedByAge']['50+']}}</th>
        <th>{{$data['everRegistared']['adults']['males']['disaggregatedByAge']['50+']}}</th>
    </tr>

    <tr>
        <th>Females</th>
        <th></th>
        <th>{{$data['txCurrent']['adults']['females']['count']}}</th>
        <th>{{$data['defaulted1Month']['adults']['females']['count']}}</th>
        <th>{{$data['defaulted2Months']['adults']['females']['count']}}</th>
        <th>{{$data['defaulted3MonthsPlus']['adults']['females']['count']}}</th>
        <th>{{$data['stopped']['adults']['females']['count']}}</th>
        <th>{{$data['died']['adults']['females']['count']}}</th>
        <th>{{$data['transferredOut']['adults']['females']['count']}}</th>
        <th>{{$data['everRegistared']['adults']['females']['count']}}</th>
    </tr>
    <tr>
        <th></th>
        <th>15-19</th>
        <th>{{$data['txCurrent']['adults']['females']['disaggregatedByAge']['15-19']}}</th>
        <th>{{$data['defaulted1Month']['adults']['females']['disaggregatedByAge']['15-19']}}</th>
        <th>{{$data['defaulted2Months']['adults']['females']['disaggregatedByAge']['15-19']}}</th>
        <th>{{$data['defaulted3MonthsPlus']['adults']['females']['disaggregatedByAge']['15-19']}}</th>
        <th>{{$data['stopped']['adults']['females']['disaggregatedByAge']['15-19']}}</th>
        <th>{{$data['died']['adults']['females']['disaggregatedByAge']['15-19']}}</th>
        <th>{{$data['transferredOut']['adults']['females']['disaggregatedByAge']['15-19']}}</th>
        <th>{{$data['everRegistared']['adults']['females']['disaggregatedByAge']['15-19']}}</th>
    </tr>
    <tr>
        <th></th>
        <th>20-24</th>
        <th>{{$data['txCurrent']['adults']['females']['disaggregatedByAge']['20-24']}}</th>
        <th>{{$data['defaulted1Month']['adults']['females']['disaggregatedByAge']['20-24']}}</th>
        <th>{{$data['defaulted2Months']['adults']['females']['disaggregatedByAge']['20-24']}}</th>
        <th>{{$data['defaulted3MonthsPlus']['adults']['females']['disaggregatedByAge']['20-24']}}</th>
        <th>{{$data['stopped']['adults']['females']['disaggregatedByAge']['20-24']}}</th>
        <th>{{$data['died']['adults']['females']['disaggregatedByAge']['20-24']}}</th>
        <th>{{$data['transferredOut']['adults']['females']['disaggregatedByAge']['20-24']}}</th>
        <th>{{$data['everRegistared']['adults']['females']['disaggregatedByAge']['20-24']}}</th>
    </tr>
    <tr>
        <th></th>
        <th>25-29</th>
        <th>{{$data['txCurrent']['adults']['females']['disaggregatedByAge']['25-29']}}</th>
        <th>{{$data['defaulted1Month']['adults']['females']['disaggregatedByAge']['25-29']}}</th>
        <th>{{$data['defaulted2Months']['adults']['females']['disaggregatedByAge']['25-29']}}</th>
        <th>{{$data['defaulted3MonthsPlus']['adults']['females']['disaggregatedByAge']['25-29']}}</th>
        <th>{{$data['stopped']['adults']['females']['disaggregatedByAge']['25-29']}}</th>
        <th>{{$data['died']['adults']['females']['disaggregatedByAge']['25-29']}}</th>
        <th>{{$data['transferredOut']['adults']['females']['disaggregatedByAge']['25-29']}}</th>
        <th>{{$data['everRegistared']['adults']['females']['disaggregatedByAge']['25-29']}}</th>
    </tr>

    <tr>
        <th></th>
        <th>30-34</th>
        <th>{{$data['txCurrent']['adults']['females']['disaggregatedByAge']['30-34']}}</th>
        <th>{{$data['defaulted1Month']['adults']['females']['disaggregatedByAge']['30-34']}}</th>
        <th>{{$data['defaulted2Months']['adults']['females']['disaggregatedByAge']['30-34']}}</th>
        <th>{{$data['defaulted3MonthsPlus']['adults']['females']['disaggregatedByAge']['30-34']}}</th>
        <th>{{$data['stopped']['adults']['females']['disaggregatedByAge']['30-34']}}</th>
        <th>{{$data['died']['adults']['females']['disaggregatedByAge']['30-34']}}</th>
        <th>{{$data['transferredOut']['adults']['females']['disaggregatedByAge']['30-34']}}</th>
        <th>{{$data['everRegistared']['adults']['females']['disaggregatedByAge']['30-34']}}</th>
    </tr>

    <tr>
        <th></th>
        <th>35-39</th>
        <th>{{$data['txCurrent']['adults']['females']['disaggregatedByAge']['35-39']}}</th>
        <th>{{$data['defaulted1Month']['adults']['females']['disaggregatedByAge']['35-39']}}</th>
        <th>{{$data['defaulted2Months']['adults']['females']['disaggregatedByAge']['35-39']}}</th>
        <th>{{$data['defaulted3MonthsPlus']['adults']['females']['disaggregatedByAge']['35-39']}}</th>
        <th>{{$data['stopped']['adults']['females']['disaggregatedByAge']['35-39']}}</th>
        <th>{{$data['died']['adults']['females']['disaggregatedByAge']['35-39']}}</th>
        <th>{{$data['transferredOut']['adults']['females']['disaggregatedByAge']['35-39']}}</th>
        <th>{{$data['everRegistared']['adults']['females']['disaggregatedByAge']['35-39']}}</th>
    </tr>

    <tr>
        <th></th>
        <th>40-44</th>
        <th>{{$data['txCurrent']['adults']['females']['disaggregatedByAge']['40-44']}}</th>
        <th>{{$data['defaulted1Month']['adults']['females']['disaggregatedByAge']['40-44']}}</th>
        <th>{{$data['defaulted2Months']['adults']['females']['disaggregatedByAge']['40-44']}}</th>
        <th>{{$data['defaulted3MonthsPlus']['adults']['females']['disaggregatedByAge']['40-44']}}</th>
        <th>{{$data['stopped']['adults']['females']['disaggregatedByAge']['40-44']}}</th>
        <th>{{$data['died']['adults']['females']['disaggregatedByAge']['40-44']}}</th>
        <th>{{$data['transferredOut']['adults']['females']['disaggregatedByAge']['40-44']}}</th>
        <th>{{$data['everRegistared']['adults']['females']['disaggregatedByAge']['40-44']}}</th>
    </tr>

    <tr>
        <th></th>
        <th>45-49</th>
        <th>{{$data['txCurrent']['adults']['females']['disaggregatedByAge']['45-49']}}</th>
        <th>{{$data['defaulted1Month']['adults']['females']['disaggregatedByAge']['45-49']}}</th>
        <th>{{$data['defaulted2Months']['adults']['females']['disaggregatedByAge']['45-49']}}</th>
        <th>{{$data['defaulted3MonthsPlus']['adults']['females']['disaggregatedByAge']['45-49']}}</th>
        <th>{{$data['stopped']['adults']['females']['disaggregatedByAge']['45-49']}}</th>
        <th>{{$data['died']['adults']['females']['disaggregatedByAge']['45-49']}}</th>
        <th>{{$data['transferredOut']['adults']['females']['disaggregatedByAge']['45-49']}}</th>
        <th>{{$data['everRegistared']['adults']['females']['disaggregatedByAge']['45-49']}}</th>
    </tr>
    <tr>
        <th></th>
        <th>50+</th>
        <th>{{$data['txCurrent']['adults']['females']['disaggregatedByAge']['50+']}}</th>
        <th>{{$data['defaulted1Month']['adults']['females']['disaggregatedByAge']['50+']}}</th>
        <th>{{$data['defaulted2Months']['adults']['females']['disaggregatedByAge']['50+']}}</th>
        <th>{{$data['defaulted3MonthsPlus']['adults']['females']['disaggregatedByAge']['50+']}}</th>
        <th>{{$data['stopped']['adults']['females']['disaggregatedByAge']['50+']}}</th>
        <th>{{$data['died']['adults']['females']['disaggregatedByAge']['50+']}}</th>
        <th>{{$data['transferredOut']['adults']['females']['disaggregatedByAge']['50+']}}</th>
        <th>{{$data['everRegistared']['adults']['females']['disaggregatedByAge']['50+']}}</th>
    </tr>

    <tr>
        <th>Pediatrics</th>
        <th></th>
        <th>{{$data['txCurrent']['pediatrics']['count']}}</th>
        <th>{{$data['defaulted1Month']['pediatrics']['count']}}</th>
        <th>{{$data['defaulted2Months']['pediatrics']['count']}}</th>
        <th>{{$data['defaulted3MonthsPlus']['pediatrics']['count']}}</th>
        <th>{{$data['stopped']['pediatrics']['count']}}</th>
        <th>{{$data['died']['pediatrics']['count']}}</th>
        <th>{{$data['transferredOut']['pediatrics']['count']}}</th>
        <th>{{$data['everRegistared']['pediatrics']['count']}}</th>
    </tr>
    <tr>
        <th>Males</th>
        <th></th>
        <th>{{$data['txCurrent']['pediatrics']['males']['count']}}</th>
        <th>{{$data['defaulted1Month']['pediatrics']['males']['count']}}</th>
        <th>{{$data['defaulted2Months']['pediatrics']['males']['count']}}</th>
        <th>{{$data['defaulted3MonthsPlus']['pediatrics']['males']['count']}}</th>
        <th>{{$data['stopped']['pediatrics']['males']['count']}}</th>
        <th>{{$data['died']['pediatrics']['males']['count']}}</th>
        <th>{{$data['transferredOut']['pediatrics']['males']['count']}}</th>
        <th>{{$data['everRegistared']['pediatrics']['males']['count']}}</th>
    </tr>
    <tr>
        <th></th>
        <th>&lt;1</th>
        <th>{{$data['txCurrent']['pediatrics']['males']['disaggregatedByAge']['<1']}}</th>
        <th>{{$data['defaulted1Month']['pediatrics']['males']['disaggregatedByAge']['<1']}}</th>
        <th>{{$data['defaulted2Months']['pediatrics']['males']['disaggregatedByAge']['<1']}}</th>
        <th>{{$data['defaulted3MonthsPlus']['pediatrics']['males']['disaggregatedByAge']['<1']}}</th>
        <th>{{$data['stopped']['pediatrics']['males']['disaggregatedByAge']['<1']}}</th>
        <th>{{$data['died']['pediatrics']['males']['disaggregatedByAge']['<1']}}</th>
        <th>{{$data['transferredOut']['pediatrics']['males']['disaggregatedByAge']['<1']}}</th>
        <th>{{$data['everRegistared']['pediatrics']['males']['disaggregatedByAge']['<1']}}</th>
    </tr>
    <tr>
        <th></th>
        <th>1-4</th>
        <th>{{$data['txCurrent']['pediatrics']['males']['disaggregatedByAge']['1-4']}}</th>
        <th>{{$data['defaulted1Month']['pediatrics']['males']['disaggregatedByAge']['1-4']}}</th>
        <th>{{$data['defaulted2Months']['pediatrics']['males']['disaggregatedByAge']['1-4']}}</th>
        <th>{{$data['defaulted3MonthsPlus']['pediatrics']['males']['disaggregatedByAge']['1-4']}}</th>
        <th>{{$data['stopped']['pediatrics']['males']['disaggregatedByAge']['1-4']}}</th>
        <th>{{$data['died']['pediatrics']['males']['disaggregatedByAge']['1-4']}}</th>
        <th>{{$data['transferredOut']['pediatrics']['males']['disaggregatedByAge']['1-4']}}</th>
        <th>{{$data['everRegistared']['pediatrics']['males']['disaggregatedByAge']['1-4']}}</th>
    </tr>
    <tr>
        <th></th>
        <th>5-9</th>
        <th>{{$data['txCurrent']['pediatrics']['males']['disaggregatedByAge']['5-9']}}</th>
        <th>{{$data['defaulted1Month']['pediatrics']['males']['disaggregatedByAge']['5-9']}}</th>
        <th>{{$data['defaulted2Months']['pediatrics']['males']['disaggregatedByAge']['5-9']}}</th>
        <th>{{$data['defaulted3MonthsPlus']['pediatrics']['males']['disaggregatedByAge']['5-9']}}</th>
        <th>{{$data['stopped']['pediatrics']['males']['disaggregatedByAge']['5-9']}}</th>
        <th>{{$data['died']['pediatrics']['males']['disaggregatedByAge']['5-9']}}</th>
        <th>{{$data['transferredOut']['pediatrics']['males']['disaggregatedByAge']['5-9']}}</th>
        <th>{{$data['everRegistared']['pediatrics']['males']['disaggregatedByAge']['5-9']}}</th>
    </tr>

    <tr>
        <th></th>
        <th>10-14</th>
        <th>{{$data['txCurrent']['pediatrics']['males']['disaggregatedByAge']['10-14']}}</th>
        <th>{{$data['defaulted1Month']['pediatrics']['males']['disaggregatedByAge']['10-14']}}</th>
        <th>{{$data['defaulted2Months']['pediatrics']['males']['disaggregatedByAge']['10-14']}}</th>
        <th>{{$data['defaulted3MonthsPlus']['pediatrics']['males']['disaggregatedByAge']['10-14']}}</th>
        <th>{{$data['stopped']['pediatrics']['males']['disaggregatedByAge']['10-14']}}</th>
        <th>{{$data['died']['pediatrics']['males']['disaggregatedByAge']['10-14']}}</th>
        <th>{{$data['transferredOut']['pediatrics']['males']['disaggregatedByAge']['10-14']}}</th>
        <th>{{$data['everRegistared']['pediatrics']['males']['disaggregatedByAge']['10-14']}}</th>
    </tr>

    <tr>
        <th>Females</th>
        <th></th>
        <th>{{$data['txCurrent']['pediatrics']['females']['count']}}</th>
        <th>{{$data['defaulted1Month']['pediatrics']['females']['count']}}</th>
        <th>{{$data['defaulted2Months']['pediatrics']['females']['count']}}</th>
        <th>{{$data['defaulted3MonthsPlus']['pediatrics']['females']['count']}}</th>
        <th>{{$data['stopped']['pediatrics']['females']['count']}}</th>
        <th>{{$data['died']['pediatrics']['females']['count']}}</th>
        <th>{{$data['transferredOut']['pediatrics']['females']['count']}}</th>
        <th>{{$data['everRegistared']['pediatrics']['females']['count']}}</th>
    </tr>
    <tr>
        <th></th>
        <th>&lt;1</th>
        <th>{{$data['txCurrent']['pediatrics']['females']['disaggregatedByAge']['<1']}}</th>
        <th>{{$data['defaulted1Month']['pediatrics']['females']['disaggregatedByAge']['<1']}}</th>
        <th>{{$data['defaulted2Months']['pediatrics']['females']['disaggregatedByAge']['<1']}}</th>
        <th>{{$data['defaulted3MonthsPlus']['pediatrics']['females']['disaggregatedByAge']['<1']}}</th>
        <th>{{$data['stopped']['pediatrics']['females']['disaggregatedByAge']['<1']}}</th>
        <th>{{$data['died']['pediatrics']['females']['disaggregatedByAge']['<1']}}</th>
        <th>{{$data['transferredOut']['pediatrics']['females']['disaggregatedByAge']['<1']}}</th>
        <th>{{$data['everRegistared']['pediatrics']['females']['disaggregatedByAge']['<1']}}</th>
    </tr>
    <tr>
        <th></th>
        <th>1-4</th>
        <th>{{$data['txCurrent']['pediatrics']['females']['disaggregatedByAge']['1-4']}}</th>
        <th>{{$data['defaulted1Month']['pediatrics']['females']['disaggregatedByAge']['1-4']}}</th>
        <th>{{$data['defaulted2Months']['pediatrics']['females']['disaggregatedByAge']['1-4']}}</th>
        <th>{{$data['defaulted3MonthsPlus']['pediatrics']['females']['disaggregatedByAge']['1-4']}}</th>
        <th>{{$data['stopped']['pediatrics']['females']['disaggregatedByAge']['1-4']}}</th>
        <th>{{$data['died']['pediatrics']['females']['disaggregatedByAge']['1-4']}}</th>
        <th>{{$data['transferredOut']['pediatrics']['females']['disaggregatedByAge']['1-4']}}</th>
        <th>{{$data['everRegistared']['pediatrics']['females']['disaggregatedByAge']['1-4']}}</th>
    </tr>
    <tr>
        <th></th>
        <th>5-9</th>
        <th>{{$data['txCurrent']['pediatrics']['females']['disaggregatedByAge']['5-9']}}</th>
        <th>{{$data['defaulted1Month']['pediatrics']['females']['disaggregatedByAge']['5-9']}}</th>
        <th>{{$data['defaulted2Months']['pediatrics']['females']['disaggregatedByAge']['5-9']}}</th>
        <th>{{$data['defaulted3MonthsPlus']['pediatrics']['females']['disaggregatedByAge']['5-9']}}</th>
        <th>{{$data['stopped']['pediatrics']['females']['disaggregatedByAge']['5-9']}}</th>
        <th>{{$data['died']['pediatrics']['females']['disaggregatedByAge']['5-9']}}</th>
        <th>{{$data['transferredOut']['pediatrics']['females']['disaggregatedByAge']['5-9']}}</th>
        <th>{{$data['everRegistared']['pediatrics']['females']['disaggregatedByAge']['5-9']}}</th>
    </tr>

    <tr>
        <th></th>
        <th>10-14</th>
        <th>{{$data['txCurrent']['pediatrics']['females']['disaggregatedByAge']['10-14']}}</th>
        <th>{{$data['defaulted1Month']['pediatrics']['females']['disaggregatedByAge']['10-14']}}</th>
        <th>{{$data['defaulted2Months']['pediatrics']['females']['disaggregatedByAge']['10-14']}}</th>
        <th>{{$data['defaulted3MonthsPlus']['pediatrics']['females']['disaggregatedByAge']['10-14']}}</th>
        <th>{{$data['stopped']['pediatrics']['females']['disaggregatedByAge']['10-14']}}</th>
        <th>{{$data['died']['pediatrics']['females']['disaggregatedByAge']['10-14']}}</th>
        <th>{{$data['transferredOut']['pediatrics']['females']['disaggregatedByAge']['10-14']}}</th>
        <th>{{$data['everRegistared']['pediatrics']['females']['disaggregatedByAge']['10-14']}}</th>
    </tr>
    <tr>
        <th>Unknown Age</th>
        <th></th>
        <th>{{$data['txCurrent']['unknownAge']['count']}}</th>
        <th>{{$data['defaulted1Month']['unknownAge']['count']}}</th>
        <th>{{$data['defaulted2Months']['unknownAge']['count']}}</th>
        <th>{{$data['defaulted3MonthsPlus']['unknownAge']['count']}}</th>
        <th>{{$data['stopped']['unknownAge']['count']}}</th>
        <th>{{$data['died']['unknownAge']['count']}}</th>
        <th>{{$data['transferredOut']['unknownAge']['count']}}</th>
        <th>{{$data['everRegistared']['unknownAge']['count']}}</th>
    </tr>
    <tr>
        <th>Males</th>
        <th></th>
        <th>{{$data['txCurrent']['unknownAge']['males']}}</th>
        <th>{{$data['defaulted1Month']['unknownAge']['males']}}</th>
        <th>{{$data['defaulted2Months']['unknownAge']['males']}}</th>
        <th>{{$data['defaulted3MonthsPlus']['unknownAge']['males']}}</th>
        <th>{{$data['stopped']['unknownAge']['males']}}</th>
        <th>{{$data['died']['unknownAge']['males']}}</th>
        <th>{{$data['transferredOut']['unknownAge']['males']}}</th>
        <th>{{$data['everRegistared']['unknownAge']['males']}}</th>
    </tr>
    <tr>
        <th>Females</th>
        <th></th>
        <th>{{$data['txCurrent']['unknownAge']['females']}}</th>
        <th>{{$data['defaulted1Month']['unknownAge']['females']}}</th>
        <th>{{$data['defaulted2Months']['unknownAge']['females']}}</th>
        <th>{{$data['defaulted3MonthsPlus']['unknownAge']['females']}}</th>
        <th>{{$data['stopped']['unknownAge']['females']}}</th>
        <th>{{$data['died']['unknownAge']['females']}}</th>
        <th>{{$data['transferredOut']['unknownAge']['females']}}</th>
        <th>{{$data['everRegistared']['unknownAge']['females']}}</th>
    </tr>
    </tbody>
</table>
